dataset:
  mot_dir: "/storage/slurm/seidensc/datasets/MOT/MOT17" 
  det_dir: "/storage/slurm/seidensc/datasets/MOT/MOT17Labels"
  det_file: "qdtrack.txt"  # byte_val.txt # bytetrack_text.txt
  detector: "FRCNN" # "all"
  splits: "mot17_train_test" #"debug_train_test" #"mot17_test" #"mot17_train_test"
  validation_set: 0
  half_train_set_gt: 0 
  gt_assign_min_iou: 0.5
  sz_crop: [384, 128]
  fixed_aspect_ratio: 0

reid_net:
  mode: 'hyper_search'
  output: 'plain'
  trained_on:
    name: 'Market'
    num_classes: 2820 #751
  encoder_params:
    pretrained_path: 'ReID/trained_models/market_models/resnet50_Market.pth'
    net_type: "resnet50" # "IBN" #
    add_distractors: 0
    neck: 0
    red: 4
    pool: 'max'

tracker:
  kalman: 0
  visualize: 0
  store_feats: 0
  use_bism: 0
  nan_first: 0
  assign_separately: 0
  random_patches_several_frames: 0
  several_frames: 0
  every_frame_several_frames: 0
  random_patches: 0
  random_patches_first: 0
  running_mean_seq: 0
  running_mean_seq_reset: 0
  first_batch: 0
  first_batch_reset: 0
  first_all: 0
  eval_bb: 0
  act_reid_thresh: 0.7
  inact_reid_thresh: 0.75
  det_conf: 0.5
  new_track_conf: 0.55
  inact_patience: 10000000
  output_dir: 'out' 
  avg_act:
    do: 0
    num: 0.95
    proxy: 'min_ioa'
  avg_inact: 
    do: 1
    num: 2
    proxy: 'each_sample'
  h_w_thresh: 1000000
  length_thresh: 1
  new_track_thresh: 0.6
  distance: 'cosine'
  motion_config:
    motion_compensation: 0
    num_iter_mc: 100
    warp_mode: 'Euclidean'
    termination_eps_mc: 0.00001
    apply_motion_model: 1
    center_only: 0
    combi: 'sum'
